name: Build
on: [push]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g cordova
      - run: cordova platform add android
      - run: cordova build android --release
      - uses: actions/upload-artifact@v4
        with:
          name: ProStore-APK
          path: platforms/android/app/build/outputs/apk/release/*.apk
      
